CONNECT SUPERMARKETCHAIN;

-- Creating the VENDORS table and filling it with data 
CREATE TABLE VENDORS
(
  V_ID NUMBER(10) NOT NULL,
  VENDOR_NAME NVARCHAR2(100),
  CONSTRAINT PK_VENDOR_ID PRIMARY KEY (V_ID)
);

CREATE SEQUENCE VENDORS_SEQ
MINVALUE 10
START WITH 10
INCREMENT BY 10
CACHE 10;

CREATE OR REPLACE TRIGGER TRIG_VEND
BEFORE INSERT ON VENDORS
FOR EACH ROW
  BEGIN 
    SELECT VENDORS_SEQ.NEXTVAL
    INTO :new.V_ID
    FROM dual;
  END;
 
BEGIN  
  INSERT ALL
    INTO VENDORS (VENDOR_NAME) VALUES ('Nestle Sofia Corp.')
    INTO VENDORS (VENDOR_NAME) VALUES ('Zagorka Corp.')
    INTO VENDORS (VENDOR_NAME) VALUES ('Targovishte Bottling Company Ltd.')
    INTO VENDORS (VENDOR_NAME) VALUES ('Coca-Cola Company')
    INTO VENDORS (VENDOR_NAME) VALUES ('James B. Beam Distilling Co.')
    INTO VENDORS (VENDOR_NAME) VALUES ('John Walker and Sons 2015')
    INTO VENDORS (VENDOR_NAME) VALUES ('Kamenitza Ltd.')
    INTO VENDORS (VENDOR_NAME) VALUES ('Prestige 96 Ltd.')
    INTO VENDORS (VENDOR_NAME) VALUES ('Mekler Ltd.')
    INTO VENDORS (VENDOR_NAME) VALUES ('Vereya Corp.')
    INTO VENDORS (VENDOR_NAME) VALUES ('Johnson and Johnson Services, Inc.')
    INTO VENDORS (VENDOR_NAME) VALUES ('LOreal Paris, Inc.')
    INTO VENDORS (VENDOR_NAME) VALUES ('Rauch Fruchtsafte GmbH and Co OG')
    INTO VENDORS (VENDOR_NAME) VALUES ('H.J. Heinz Co. (HNZ)')
    INTO VENDORS (VENDOR_NAME) VALUES ('SuiCo EOOD')
    INTO VENDORS (VENDOR_NAME) VALUES ('Frito-Lay North America, Inc.')
    INTO VENDORS (VENDOR_NAME) VALUES ('DEVIN JSC')
    INTO VENDORS (VENDOR_NAME) VALUES ('Aroma PLC')
    INTO VENDORS (VENDOR_NAME) VALUES ('The Procter and Gamble Company')
    INTO VENDORS (VENDOR_NAME) VALUES ('Beiersdorf Inc (NIVEA)')
    INTO VENDORS (VENDOR_NAME) VALUES ('Costa dOro S.p.A.')
    SELECT * FROM dual
    COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX
  THEN ROLLBACK;
END;


-- Creating the MEASURE_UNITS and filling it with data
CREATE TABLE MEASURE_UNITS
(
  M_ID NUMBER(10) NOT NULL,
  MEASURE_NAME NVARCHAR2(100),
  CONSTRAINT PK_MEASURE_ID PRIMARY KEY (M_ID)
);

CREATE SEQUENCE MEASURE_UNITS_SEQ
MINVALUE 100
START WITH 100
INCREMENT BY 100
CACHE 10;

CREATE OR REPLACE TRIGGER TRIG_MEASURE_UNITS
BEFORE INSERT ON MEASURE_UNITS
FOR EACH ROW
  BEGIN 
    SELECT MEASURE_UNITS_SEQ.NEXTVAL
    INTO :new.M_ID
    FROM dual;
  END;

BEGIN
  INSERT ALL
    INTO MEASURE_UNITS (MEASURE_NAME) VALUES ('liters')
    INTO MEASURE_UNITS (MEASURE_NAME) VALUES ('pieces')
    INTO MEASURE_UNITS (MEASURE_NAME) VALUES ('kg')

    SELECT * FROM dual
    COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX
  THEN ROLLBACK;
END;
    

-- Creating the PRODUCTS table and filling with data
CREATE TABLE PRODUCTS
(
  P_ID NUMBER(10) NOT NULL,
  VENDOR_ID NUMBER(10),
  PRODUCT_NAME NVARCHAR2(100),
  MEASURE_ID NUMBER(10),
  PRICE DECIMAL(19,4),
  PRODUCT_TYPE NVARCHAR2(100),
  CONSTRAINT PK_PRODUCT_ID PRIMARY KEY (P_ID),
  CONSTRAINT FK_VENDORS FOREIGN KEY (VENDOR_ID) REFERENCES VENDORS(V_ID),
  CONSTRAINT FK_MEASURES FOREIGN KEY (MEASURE_ID) REFERENCES MEASURE_UNITS(M_ID)
);

CREATE SEQUENCE PROD_SEQ
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE OR REPLACE TRIGGER TRIG_PROD
  BEFORE INSERT ON PRODUCTS
  FOR EACH ROW
    BEGIN 
      SELECT PROD_SEQ.NEXTVAL
      INTO :new.P_ID
      FROM dual;
    END;
    
BEGIN
  INSERT ALL
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (20, 'Beer “Zagorka”', 100, 0.86, 'alcohol drinks')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (30, 'Vodka “Targovishte”', 100, 7.56, 'alcohol drinks')          
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (20, 'Beer “Beck’s”', 100, 1.03, 'alcohol drinks')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (10, 'Chocolate “Milka”', 200, 2.80, 'confectionery')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (40, 'Coca-Cola 2l', 100, 2.50, 'non-alcohol drinks')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (50, 'Jim Beam', 100, 20, 'alcohol drinks')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (70, 'Kamenitza', 100, 1.25, 'alcohol drinks')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (10, 'Nesquik 200g', 300, 4.15, 'non-alcohol drinks')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (10, 'Kit-Kat 90g', 300, 1.00, 'confectionery')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (10, 'Nescafe 250g', 300, 9.50, 'non-alcohol drinks')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (80, 'Cereal with chocolate', 300, 2.00, 'food')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (80, 'Oatmeal cereal', 300, 2.10, 'food')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (80, 'Cereal with apple and walnut', 300, 2.00, 'food')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (90, 'Rodopsko Chudo cheese', 300, 8.60, 'food')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (90, 'Ovcho Narodno cheese', 300, 8.40, 'food')         
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (180, 'Aroma Vital Exfoliating soap 100g', 200, 0.99, 'body care')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (170, 'Devin Mineral Water 10l', 100, 3.99, 'non-alcohol drinks')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (170, 'Devin Mineral Water 1.5l', 100, 0.85, 'non-alcohol drinks')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (110, 'JOHNSON’S baby HEAD-TO-TOE wash shampoo 444ml', 
                    200, 3.15, 'body care')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (110, 'JOHNSON’S baby moisture wash with honey apple shampoo 444ml', 
                    200, 3.15, 'body care')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (210, 'Costa d`Oro 1l', 200, 13.59, 'food')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (100, 'Yoghurt 2% 500g', 200, 0.85, 'food')    
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (100, 'Yoghurt 0.1% 450g', 200, 0.90, 'food')  
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (190, 'Head ' || chr(38) || ' Shoulders', 200, 5.35, 'body care')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (140, 'Happy Day 100% Orange 1l', 200, 2.30, 'non-alcohol drinks')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (10, 'Heinz Tomato Ketchup', 200, 4.80, 'food')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (200, 'NIVEA honey ' || chr(38) || ' oil soap', 200, 0.90, 'body care')
    INTO PRODUCTS (VENDOR_ID, PRODUCT_NAME, MEASURE_ID, PRICE, PRODUCT_TYPE) 
          VALUES  (180, 'Natural Elements Red Fruits soap 100g', 200, 0.99, 'body care')            
    SELECT * FROM dual  
    COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX
  THEN ROLLBACK;
END;

CREATE VIEW PRODUCTS_VENDORS_MEASURES
AS
  SELECT p.P_ID, p.PRODUCT_NAME, p.PRICE, m.MEASURE_NAME, p.PRODUCT_TYPE, v.VENDOR_NAME
  FROM PRODUCTS p
  INNER JOIN MEASURE_UNITS m ON m.M_ID = p.MEASURE_ID
  INNER JOIN VENDORS v ON v.V_ID = p.VENDOR_ID
  ORDER BY p.P_ID;
  
-- SELECT * FROM PRODUCTS_VENDORS_MEASURES;  